### PR TITLE
Add the composition of the PSC over time

### PR DESCRIPTION
**Pull request by book**
In reverse chronological order, just like the default for the PSC meeting minutes.

### CODE REVIEW

**Comment by book** [comment]
I just realized this is only touching the README. Should that information also be published on the web site?

**Comment by davorg** [comment]
Coincidentally, this is an addition I've been thinking about over the last few days. 

But, yeah, I'd rather it was a new "about the PSC" page on the site. 

If you don't have the time to do this, I'll pick it up in the morning - using the information you've given me here.

Thanks for showing an interest in the site.

**Comment by book** [comment]
I'm sure you'll figure out the best way to integrate that information in the web site.

**Comment by book** [comment]
Sorry, was fiddling around with the branches, and that seem to have closed the PR.

For reference, I've created a new branch pointing to this commit: https://github.com/book/psc/tree/psc-members

**Comment by davorg** [comment]
Done in b6d3b91e907354cae8e797926b067fa7009e3381

**Pull request closed without merging**
